using Foundation;
using ObjCRuntime;

namespace Firebase.AppCheck;

public partial class AppCheck
{
	/// <summary>
	/// Calls FIRAppCheck.setAppCheckProviderFactory: using ApiDefinition.Messaging.
	/// This bypasses C# protocol interface cast issues that occur at runtime with ObjC bindings.
	/// Uses the same pattern as auto-generated binding code.
	/// </summary>
	private static void SetAppCheckProviderFactoryNative(NSObject factory)
	{
		// Call: +[FIRAppCheck setAppCheckProviderFactory:]
		// Using ApiDefinition.Messaging (generated by binding tooling, same as ObjCRuntime.Messaging pattern)
		global::ApiDefinition.Messaging.void_objc_msgSend_NativeHandle(
			Class.GetHandle("FIRAppCheck"),
			Selector.GetHandle("setAppCheckProviderFactory:"),
			factory?.GetNonNullHandle(nameof(factory)) ?? default);
	}

	public static void SetAppCheckProviderFactory(AppCheckDebugProviderFactory factory)
	{
		SetAppCheckProviderFactoryNative(factory);
	}

	public static void SetAppCheckProviderFactory(DeviceCheckProviderFactory factory)
	{
		SetAppCheckProviderFactoryNative(factory);
	}
}
